---
sudo: false
language: ruby
python: "2.7"

# Install ansible
addons:
  apt:
    packages:
    - python-pip
rvm:
  - 2.3.5
before_install:

  # use bundler 2.x
  - gem install bundler
  - pip install --user ansible
  - ansible --version
